{
 "title": "Fleet Manager - Drones",
 "panels": [
  {
   "title": "Lista de Vehículos",
   "type": "table",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "targets": [
    {
     "rawSql": "SELECT vehicle_id, name, created_at FROM vehicles"
    }
   ]
  },
  {
   "title": "Velocidad - Última Hora",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "rawSql": "SELECT received_at as time, linear_speed FROM drone_states WHERE vehicle_id = $vehicle_id AND received_at > NOW() - INTERVAL 1 HOUR ORDER BY received_at"
    }
   ]
  },
  {
   "title": "Batería - Última Hora",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "rawSql": "SELECT received_at as time, battery_percentage * 100 FROM drone_states WHERE vehicle_id = $vehicle_id AND received_at > NOW() - INTERVAL 1 HOUR ORDER BY received_at"
    }
   ]
  },
  {
   "title": "Orientación (Roll/Pitch/Yaw) - Última Hora",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 24, "h": 8 },
   "targets": [
    {
     "legendFormat": "Roll",
     "rawSql": "SELECT received_at as time, roll FROM drone_states WHERE vehicle_id = $vehicle_id AND received_at > NOW() - INTERVAL 1 HOUR ORDER BY received_at"
    },
    {
     "legendFormat": "Pitch",
     "rawSql": "SELECT received_at as time, pitch FROM drone_states WHERE vehicle_id = $vehicle_id AND received_at > NOW() - INTERVAL 1 HOUR ORDER BY received_at"
    },
    {
     "legendFormat": "Yaw",
     "rawSql": "SELECT received_at as time, yaw FROM drone_states WHERE vehicle_id = $vehicle_id AND received_at > NOW() - INTERVAL 1 HOUR ORDER BY received_at"
    }
   ]
  },
  {
   "title": "Velocidad - Última Semana",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 24, "w": 12, "h": 8 },
   "targets": [
    {
     "rawSql": "SELECT received_at as time, AVG(linear_speed) as speed FROM drone_states WHERE vehicle_id = $vehicle_id AND received_at > NOW() - INTERVAL 1 WEEK GROUP BY FLOOR(UNIX_TIMESTAMP(received_at)/3600) ORDER BY received_at"
    }
   ]
  },
  {
   "title": "Batería - Última Semana",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 24, "w": 12, "h": 8 },
   "targets": [
    {
     "rawSql": "SELECT received_at as time, AVG(battery_percentage) * 100 as battery FROM drone_states WHERE vehicle_id = $vehicle_id AND received_at > NOW() - INTERVAL 1 WEEK GROUP BY FLOOR(UNIX_TIMESTAMP(received_at)/3600) ORDER BY received_at"
    }
   ]
  }
 ]
}